name: Publish package to the Maven Central Repository
on:
#  release:
#    types: [created]
  push:
    branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: List of keys on gpg
        run: gpg --list-secret-keys --keyid-format LONG
#      - name: Publish to the Maven Central Repository
#        run: |
#          export GPG_TTY=$(tty)
#          gpg --pinentry-mode loopback --passphrase '${{ secrets.GPG_IV }}' -s pom.xml
#          mvn --batch-mode deploy -P ossrh
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_IV }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v3
#        with:
#          java-version: 8
#          distribution: 'adopt'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy -P github
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
